// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67gv4aO2o8yJPjrsaTMlAGBKXCXqxAoU',
    appId: '1:816213246165:web:9aa9d492de7e832db1a25c',
    messagingSenderId: '816213246165',
    projectId: 'vtrack-fleet-management-app',
    authDomain: 'vtrack-fleet-management-app.firebaseapp.com',
    databaseURL: 'https://vtrack-fleet-management-app-default-rtdb.firebaseio.com',
    storageBucket: 'vtrack-fleet-management-app.firebasestorage.app',
    measurementId: 'G-S7FWGPGJ8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQRZrx7M231fTFAcUEkAh7yl8meu2Eko0',
    appId: '1:816213246165:android:08cf3014dc1e3d32b1a25c',
    messagingSenderId: '816213246165',
    projectId: 'vtrack-fleet-management-app',
    databaseURL: 'https://vtrack-fleet-management-app-default-rtdb.firebaseio.com',
    storageBucket: 'vtrack-fleet-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRZrx7M231fTFAcUEkAh7yl8meu2Eko0',
    appId: '1:816213246165:android:08cf3014dc1e3d32b1a25c',
    messagingSenderId: '816213246165',
    projectId: 'vtrack-fleet-management-app',
    databaseURL: 'https://vtrack-fleet-management-app-default-rtdb.firebaseio.com',
    storageBucket: 'vtrack-fleet-management-app.firebasestorage.app',
    iosBundleId: 'com.fleetmanagement.manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQRZrx7M231fTFAcUEkAh7yl8meu2Eko0',
    appId: '1:816213246165:android:08cf3014dc1e3d32b1a25c',
    messagingSenderId: '816213246165',
    projectId: 'vtrack-fleet-management-app',
    databaseURL: 'https://vtrack-fleet-management-app-default-rtdb.firebaseio.com',
    storageBucket: 'vtrack-fleet-management-app.firebasestorage.app',
    iosBundleId: 'com.fleetmanagement.manager',
  );
}
